config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'products#index'
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/password',
      registrations: 'admins/registrations'
    }
    devise_for :end_users, controllers: {
      sessions:      'end_users/sessions',
      password:      'end_users/password',
      registrations: 'end_users/registrations'
    }
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
    resources :order_details, only: [:index]
    end
    resources :orders, only: [:index, :show, :update]

    resources :products, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :arrivals, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :artists, only: [:new, :edit, :create, :update, :destroy]
    resources :labels, only: [:new, :edit, :create, :update, :destroy]
    resources :genres, only: [:new, :edit, :create, :update, :destroy]

    get  'top' => 'homes#top'
    get  'out/end_users/:id', to: 'end_users#out', as: :out
    get  'change' => 'order_details#change'
  end   
  resources :end_users, only: [:show, :edit, :destroy, :update] do 
    resources :addresses, only: [:create]
  end
  post '/orders/confirm', to: 'orders#before_confirm'
  get '/orders/confirm', to: 'orders#confirm', as: :confirm_order
  get '/orders/finish', to: 'orders#finish', as: :finish_order
  resources :orders, only: [:index, :show, :new, :create]
  resources :order_details, only: [:index]
  resources :cart_products, only: [:index, :update, :create, :destroy]
  resources :products, only: [:index, :show]
  get  'out' => 'end_users#out'
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :end_user
    belongs_to :product

    validates :quantity, :numericality => { :greater_than_or_equal_to => 1 }, presence: true

    def total_arrival_quantity
        total_arrival_quantity = 0
        arrivals.each do |arrival|
            total_arrival_quantity = arrival.quantity + total_arrival_quantity
        end
        total_arrival_quantity
    end

    def total_order_detail_quantity
        total_order_detail_quantity = 0
        order_details.each do |order_detail|
            unless order_detail.quantity.nil?
                total_order_detail_quantity = order_detail.quantity + total_order_detail_quantity
            
        end
        total_order_detail_quantity
    end

end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
    before_action :authenticate_end_user!
    
def index
    @cart_product = current_end_user.cart_products
end
def update
    cart_product = CartProduct.find(params[:id])
    cart_product.quantity =  params[:cart_product][:quantity].to_i
    cart_product.save
    redirect_to cart_products_path
end
def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_products_path
end 
def create
    cart_product = CartProduct.new(end_user_id: current_end_user.id, product_id: params[:cart_product][:product_id], quantity: params[:cart_product][:quantity] )
    cart_product.save
    redirect_to cart_products_path
end

end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/edit.html.erb
<div class="container">
<h1>カート内商品編集</h1>
    <div class="row">
        <div class="col-sm-8">
            <% total_quantity = 0%>
            <% total_price = 0 %>
            <% current_end_user.cart_products.each do |cart_product|%>
                <div>
                    <%= attachment_image_tag cart_product.product.image, :fill, 80, 80, format: 'jpeg', class: "img-circle pull-left profile-img" %>
                    <h2>シングル/アルバム名</h2>
                    <%= cart_product.product.title %>
                    <hr>
                    <h2>在庫ありかどうかの表示</h2>
                    <%= cart_product.product.status %>
                    <hr>
                    <%= form_for cart_product, url: "/cart_products/#{cart_product.id}" ,method: :PUT do |f| %>
                        <h2>数量</h2>
                        <%= f.number_field :quantity %>
                        <%= f.submit 'この内容で更新する' %>
                    <% end %>
                    <hr>
                        <h2>小計（税込）</h2>
                    ¥ <%= cart_product.product.amount * cart_product.quantity %>
                        <h2>合計枚数</h2>
                    <%= total_quantity += cart_product.quantity %>
                        <h2>合計金額</h2>
                    <%= total_price += cart_product.product.amount * cart_product.quantity %>
                </div>
            <% end %>
        </div>
        <div class="col-sm-4">
            <h2>合計枚数</h2>
            <%= total_quantity %>
            <h2>合計（税込）</h2>
            <%= total_price %>
            </tr>
            <h2>送料</h2>
            <h2>+ ¥500</h2>
        </div>
        <hr>
        <div class="button_wrapper">
        <%= link_to new_order_path, class: "center-block" do %>
                <button type="button" class="btn btn-default">レジに進む</button>
        </div>
        <% end %>
    </div>  <%#rowの閉じタグ%>
</div>  <%#containerの閉じタグ%>

app/views/cart_products/index.html.erb
<div class="container">
<h1>カート内商品編集</h1>
<br>
<% if current_end_user.cart_products.blank? %>
    <h1 class="alert alert-success">商品を選択してください</h1>
<% end %>
<br>
    <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-6">
            <% total_quantity = 0 %>
            <% total_price = 0 %>
            <% current_end_user.cart_products.each do |cart_product|%>
                <div>
                    <%= attachment_image_tag cart_product.product, :image, :fill, 100, 100, fallback: "default_product.jpg" , size:'100x100'  %>
                    <br>
                    <br>
                    <%# <h2>シングル/アルバム名</h2> %>
                    <h2><%= cart_product.product.title %></h2>
                    <hr>
                    <%# 在庫数の計算式です。 %>
                    <% productquantity = cart_product.product.arrivals.sum(:quantity) - cart_product.product.order_details.sum(:quantity) %>
                    <h2>在庫数：<%= productquantity %>枚</h2>
                    <hr>
                    <h2>販売状況</h2>
                    <% if productquantity == 0 %>
                    <h2 class="card-title soldout">売り切れ<h2>
                    <% else %>
                    <h2 class="card-title sale">販売中</h2>
                    <% end %>
                    <hr>
                    <h2>金額：¥ <%= (cart_product.product.amount * 1.1).floor(0) %>（税込）</h2> 
                    <hr>
                    <%= form_for cart_product, url: "/cart_products/#{cart_product.id}" ,method: :PUT do |f| %>
                        <h2>数量</h2>
                        <%= f.number_field :quantity, min: 0,max: productquantity %>
                        <%= f.submit 'この内容で更新する' %>
                    <% end %>
                    <hr>
                
                    <h2>枚数：<%= cart_product.quantity %> 枚</h2>                    
                    <%# <h2>合計枚数</h2> %>
                    <% total_quantity = cart_product.quantity + total_quantity%>
                    <h2>小計：¥ <%= (cart_product.product.amount * cart_product.quantity * 1.1).floor(0) %>（税込）</h2>
                    
                    <%# <h2>合計金額</h2> %>
                    <% total_price += (cart_product.product.amount * cart_product.quantity * 1.1).floor(0) %>
                </div>
                <hr>
                <%= link_to "削除する", cart_product_path(cart_product), method: :delete, class: "btn btn-danger" %>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
            <% end %>
        </div>
        <div class="col-sm-4">
            <div class="box-line">
                <h2>合計枚数：<%= total_quantity %> 枚</h2>
                <h2>合計：¥ <%= total_price %>（税込）</h2>
                <h2>送料：+ ¥500</h2>
                <hr>
                <h2>総計：¥ <%= total_price.floor(0) + 500 %>（税込）</h2>
                
            </div>
            <br>
            <div class="button_wrapper">
                <% if total_quantity >= 1 %>
                    <%= link_to "レジに進む", new_order_path, class: "btn btn-success" %><br><br>
                    <%= link_to "お買い物を続ける", products_path, class: "btn btn-info" %>
                <% else %>
                    <%= link_to "レジに進む", cart_products_path, class: "btn btn-success" %><br><br>
                    <%= link_to "商品を選ぶ", products_path, class: "btn btn-info" %>
                <% end %>
            </div>
        </div>
    </div>  <%#rowの閉じタグ%>
</div>  <%#containerの閉じタグ%>