config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'products#index'
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/password',
      registrations: 'admins/registrations'
    }
    devise_for :end_users, controllers: {
      sessions:      'end_users/sessions',
      password:      'end_users/password',
      registrations: 'end_users/registrations'
    }
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
    resources :order_details, only: [:index]
    end
    resources :orders, only: [:index, :show, :update]

    resources :products, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :arrivals, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :artists, only: [:new, :edit, :create, :update, :destroy]
    resources :labels, only: [:new, :edit, :create, :update, :destroy]
    resources :genres, only: [:new, :edit, :create, :update, :destroy]

    get  'top' => 'homes#top'
    get  'out/end_users/:id', to: 'end_users#out', as: :out
    get  'change' => 'order_details#change'
  end   
  resources :end_users, only: [:show, :edit, :destroy, :update] do 
    resources :addresses, only: [:create]
  end
  post '/orders/confirm', to: 'orders#before_confirm'
  get '/orders/confirm', to: 'orders#confirm', as: :confirm_order
  get '/orders/finish', to: 'orders#finish', as: :finish_order
  resources :orders, only: [:index, :show, :new, :create]
  resources :order_details, only: [:index]
  resources :cart_products, only: [:index, :update, :create, :destroy]
  resources :products, only: [:index, :show]
  get  'out' => 'end_users#out'
  
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :main_postal_code, presence: true
  validates :main_address, presence: true
  validates :phone_number, presence: true
  





  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  # accepts_nested_attributes_for :addresses

  def cart_total_price
    total_price = 0
    self.cart_products.each do |cart_product|
      total_price += cart_product.product.amount * cart_product.quantity
    end
    return total_price
  end


end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < Admin::Base
    before_action :authenticate_admin!
    PER = 2

def index
    @end_user = EndUser.new
    @end_users = EndUser.with_deleted.page(params[:page]).per(PER)
end 



def show
    @enduser = EndUser.with_deleted.find(params[:id])
    @end_user = EndUser.new
end
def edit
    @enduser = EndUser.find(params[:id])
    @end_user = EndUser.new
end
def out
    @enduser = EndUser.find(params[:id])
    @end_user = EndUser.new
end

def update
    @enduser = EndUser.find(params[:id])
    if @enduser.update(end_user_params)
    redirect_to admin_end_user_path
    else 
        render :edit
    end
end
def destroy
    @enduser = EndUser.find(params[:id])
    @enduser.destroy
    redirect_to admin_end_users_path
end

private
def end_user_params
    params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :main_postal_code, :main_address, :phone_number, :email)
end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
    before_action :authenticate_end_user!
    before_action :correct_end_user, only: [:show, :edit, :update]
    
    
def show
    @end_user = EndUser.find(params[:id])
    @full_name = @end_user.last_name + @end_user.first_name
    @full_name_kana = @end_user.last_name_kana + @end_user.first_name_kana
    @phone_number = @end_user.phone_number
    @email = @end_user.email
    @main_postal_code = @end_user.main_postal_code
    @main_address = @end_user.main_address
    @addresses = @end_user.addresses
end
def edit
    @end_user = EndUser.find(params[:id])
    @newaddress = Address.new
end
def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
        flash[:end_user] = "マイページを編集しました。"
        redirect_to end_user_path(@end_user)
    else 
        @newaddress = Address.new
        render :edit
    end

end
def create
end
def out
end
def destroy
    end_user = EndUser.find(params[:id])
    end_user.destroy
    redirect_to root_path
end


private
def end_user_params
    params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :main_postal_code, :main_address, :phone_number, :email)
end

def correct_end_user
    end_user = EndUser.find(params[:id])
    if current_end_user != end_user
    redirect_to end_user_path(current_end_user.id)
    end
end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class= "container">
  <h1>ユーザー編集画面</h1>
  <%= form_for(@enduser,
              url: admin_end_user_path) do |user| %>
  <table class= "table">
    <tr><td>ユーザー名</td></tr>
    <tr>
    <td> 
      <%= user.text_field :last_name %>
      <%= user.text_field :first_name %>
    </td>
    </tr>
    <tr>
      <td>
        <%= user.text_field :last_name_kana %>
        <%= user.text_field :first_name_kana %>
      </td>
    </tr>
    <tr>
      <td>郵便番号</td>
    </tr>
    <tr>
      <td>
        <%= user.text_field :main_postal_code %>
      </td>
    </tr>
    <tr>
      <td>住所</td>
    </tr>
    <tr>
      <td><%= user.text_field :main_address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
    </tr>
    <tr>
      <td><%= user.text_field :phone_number %></td>
    </tr>
    
  </table>
  <div class= "button-wrapper">
    <%= user.submit "編集完了", class: 'btn btn-success' %>
  </div>
  <% end %>
  <br>
  <div class= "button-wrapper">
  <%= link_to "退会させる", admin_out_path(@enduser), class: 'btn btn-danger' %>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<div class= "container">
    <div class="page-header">
        <h1>ユーザー情報一覧</h1>
    </div>
    <div class="list-group">
        <table class= "table">
            <% @end_users.each do |user| %>
            <tr>
            <th>
                <%= user.last_name %>
                <%= user.first_name %>
            </th>
            <th><%= link_to admin_end_user_path(user) do %>
                <i>show</i>
                <% end %>
            </th>
            </tr>
        <% end %>
        </table>
    <div class="pagination">
        <%= paginate @end_users %>
    </div>
</div>

app/views/admin/end_users/out.html.erb
<div class= "container">
<h1>本当にこのユーザーを退会させますか？</h1>
<div class= "button_wrapper">
<%= link_to "中止する", edit_admin_end_user_path(@enduser), class: 'btn btn-warning' %>
</div>
<br>
<div class= "button_wrapper">
<%= link_to "退会させる", admin_end_user_path(@enduser.id), method: :delete, class: 'btn btn-danger' %>
</div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
<h1>ユーザー詳細画面</h1>
<table class= "table">
    <tr>
        <th>名前(漢字)</th>
        <th>
        <%= @enduser.last_name %>
        <%= @enduser.first_name %>
        </th>
    </tr>
    <tr>
        <th>名前(カタカナ)</th>
        <th>
        <%= @enduser.last_name_kana %>
        <%= @enduser.first_name_kana %>
        </th>
    </tr>
    <tr>
        <th>郵便番号</th>
        <th>
        <%= @enduser.main_postal_code %>
        </th>
    </tr>
    <tr>
        <th>住所</th>
        <th>
        <%= @enduser.main_address %>
        </th>
    </tr>
    <tr>
        <th>クレジットカード情報</th>
        <th>0000-0000-0000</th>
</tr>
<tr>
        <th>電話番号</th>
        <th>
        <%= @enduser.phone_number%> 
</table>
<%= link_to "編集画面へ", edit_admin_end_user_path(@enduser) %>
<%= link_to "受注履歴一覧へ", admin_end_user_order_details_path(@enduser) %>
</div>