config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'products#index'
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/password',
      registrations: 'admins/registrations'
    }
    devise_for :end_users, controllers: {
      sessions:      'end_users/sessions',
      password:      'end_users/password',
      registrations: 'end_users/registrations'
    }
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
    resources :order_details, only: [:index]
    end
    resources :orders, only: [:index, :show, :update]

    resources :products, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :arrivals, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :artists, only: [:new, :edit, :create, :update, :destroy]
    resources :labels, only: [:new, :edit, :create, :update, :destroy]
    resources :genres, only: [:new, :edit, :create, :update, :destroy]

    get  'top' => 'homes#top'
    get  'out/end_users/:id', to: 'end_users#out', as: :out
    get  'change' => 'order_details#change'
  end   
  resources :end_users, only: [:show, :edit, :destroy, :update] do 
    resources :addresses, only: [:create]
  end
  post '/orders/confirm', to: 'orders#before_confirm'
  get '/orders/confirm', to: 'orders#confirm', as: :confirm_order
  get '/orders/finish', to: 'orders#finish', as: :finish_order
  resources :orders, only: [:index, :show, :new, :create]
  resources :order_details, only: [:index]
  resources :cart_products, only: [:index, :update, :create, :destroy]
  resources :products, only: [:index, :show]
  get  'out' => 'end_users#out'
  
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [['---',""],['売り切れ', 1],['販売中', 2]]
    acts_as_paranoid
    def total_arrival_quantity
        total_arrival_quantity = 0
        arrivals.each do |arrival|
        total_arrival_quantity = arrival.quantity + total_arrival_quantity
            unless arrival.quantity.nil?
                total_arrival_quantity = arrival.quantity + total_arrival_quantity

            end
        end
        total_arrival_quantity
    end

    def total_order_detail_quantity
        total_order_detail_quantity = 0
        order_details.each do |order_detail|
            unless order_detail.quantity.nil?
                total_order_detail_quantity = order_detail.quantity + total_order_detail_quantity
        
            end
        end
        total_order_detail_quantity
    end

    def included_price
        included_price = (amount * 1.1).floor(0)
    end

    validates :title, presence: true
    validates :explanation, presence: true
    validates :amount, presence: true
    attachment :image

    has_many :discs, inverse_of: :product
    accepts_nested_attributes_for :discs , reject_if: :all_blank , allow_destroy: true

    belongs_to :artist 
    belongs_to :genre
    belongs_to :label
    has_many :arrivals
    has_many :order_details
    has_many :cart_products
    has_many :order_details

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::Base
    before_action :authenticate_admin!

PER = 8

def index
    @products = Product.with_deleted.page(params[:page]).per(PER)
end 

def show
    @product = Product.find(params[:id])
end

def new
    @products = Product.all
    @product = Product.new
    @disc = @product.discs.build
    @music = @disc.musics.build
    @arrival = Arrival.new
    @artists = Artist.all.order(id: "DESC")
    @artist = Artist.new
    @genres = Genre.all.order(id: "DESC")
    @genre = Genre.new
    @labels = Label.all.order(id: "DESC")
    @label = Label.new
end
def edit
    
    @product = Product.find(params[:id])
end

def create
    product = Product.new(product_params)
    if product.save
        redirect_to admin_product_path(product)
    else
        redirect_to new_admin_product_path , notice:"商品の追加に失敗しました。"
    end
end

def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to admin_product_path(product)
end

def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path
end


private
def product_params
    params.require(:product).permit(:id, :title, :image, :artist_id, :genre_id, :label_id, :amount, :explanation, :status, :destroy, discs_attributes: [:id, :disc_number, :_destroy, musics_attributes: [:id, :music_name, :_destroy]])
end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    PER = 12
    
def index
    @product = Product.new
    if params[:q]
        @products = @q.result.page(params[:page]).per(PER)
    else
        @products = Product.page(params[:page]).per(PER)

    end 
end

def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_disc_fields.html.erb
<div class="nested-fields well well-compact">
<div class="form-group">
<%= f.label :disc_number %>
<%= f.number_field :disc_number, value: 1%><br>
</div>

<div class="musics">
<%= f.fields_for :musics do |music| %>
<%= render 'music_fields', f: music %>
<% end %>
<div class="links">
<%= link_to_add_association "音楽追加欄を増やす", f, :musics %>
</div>
</div>

</div>

app/views/admin/products/_form.html.erb
<%= form_for @product do |f| %>
<div class="field">
<%= f.label :title, "シングル/アルバム名" %>
<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :explanation, "商品説明" %>
<%= f.text_field :explanation %>
</div>

<h4>ディスクの登録</h4>
<div id="discs">
<%= f.fields_for :discs do |disc| %>
<%= render 'disc_fields', f: disc %>
<% end %>
<div class="links">

<%= link_to_add_association 'ディスク追加欄を増やす',f,:discs %>
</div>

<% end %>

app/views/admin/products/_music_fields.html.erb
<div class="nested_fields form-inline">
<div class="from-group">
<%= f.label :music_name %>
<%= f.text_field :music_name %>
</div>
</div>

app/views/admin/products/edit.html.erb
<h1>商品情報の編集</h1>

<div>
<%= form_for([:admin, @product]) do |f| %>

<%= render 'form', product: @product %>

<div>ジャケット画像</div>
<p><%= f.attachment_field :image %></p>

<div>新しい商品のアーティスト</div>
<%= f.collection_select :artist_id, Artist.all, :id, :artist_name %>
<div>
<%= link_to "アーティストの追加" , new_admin_artist_path %>
</div>

<div>ジャンル</div>
<%= f.collection_select :genre_id, Genre.all, :id, :genre_name %>
<div>
<%= link_to "ジャンルの追加" , new_admin_genre_path %>
</div>

<div>レーベル</div>
<%= f.collection_select :label_id, Label.all, :id, :label_name %>
<div>
<%= link_to "レーベルの追加" , new_admin_label_path %>
</div>

<div>値段</div>
<p><%= f.text_field :amount %></p>

<%# <div>在庫数</div> %>
<%# <%= f.text_field :product %>

<%# <div>販売ステータス</div>
<p><%= f.select :status, Product.statuses.keys, {}, class: "select-default" %>

<p>
<%= f.submit '商品情報を更新する' %>
</p>

<p>
<%= link_to "商品の削除", admin_product_path(@product), method: :delete, data: {confirm: '本当に削除しますか？'} %>
</p>

<% end %>
</div>

app/views/admin/products/index.html.erb
<div class="container">
    <div class="page-header">
        <h1>商品一覧</h1>
        <br>
    </div>
    <div class="row">
        
            <% @products.each do |product| %>
            <div class="col-md-3">
                <div class="card px-2 py-1 text-center">
                
                    <img class="card img-top">
                    <%= link_to admin_product_path(product) do %>
                    <figure>
                    <%= attachment_image_tag product, :image, :fill, 170, 170, fallback: "default_product.jpg" , size:'170x170' %>
                    <% end %>
                    <div class="box">
                        <hr>
                        id:<%= product.id %>
                        
                        <div>
                            <%= product.title %>
                        </div>
                        
                        
                        <%= product.artist.artist_name %>
                        
                        
                        <div>価格 | ¥<%= product.amount %>(税抜)</div>
                        <br>
                        
                        <div>在庫数 : 
                            <%= productquantity = product.arrivals.sum(:quantity) - product.order_details.sum(:quantity) %>
                        </div>
                        <br>
                        
                        
                        
                        <% if productquantity == 0 %>
                        <div>売り切れ</div>
                        <% else %>
                        <div>販売中</div>
                        <% end %>
                        <br>
                    </div>
                    </figure>
                </div>
                <br>
            </div>
            
        
        <% end %>
    </div>
</div>
<br>
<div class="pagination">
    <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<%# <% if flash[:notice] %>
  <%# <p class="flash_color"><%= flash[:notice] %>
<%# <% end %>

<h1>新規商品登録フォーム</h1>
    <hr>
    <br>
    <br>
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <%= form_for([:admin, @product]) do |f| %>

        <%= render 'form', product: @product %>

        <div>ジャケット画像</div>
        <p><%= f.attachment_field :image %></p>

        <div>アーティストを選択</div>
        <%= f.collection_select :artist_id, Artist.all, :id, :artist_name %>

        <div class="artist_button create_artist_button">アーティストを追加する</div>



        <div>ジャンルを選択</div>
        <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %>

        <div class="new_button genre_button">ジャンルを追加する</div>

        <div class="genre_modal_wrapper">
            <div class="genre_modal genre_modal_content">
                <p class="text-right">
                <span class="fa_wrapper"><%= fa_icon "times" %></span>
                </p>
                <h1>ジャンル追加フォーム</h1>
                <h2>追加済みジャンル一覧</h2>
                <div class="genre_wrapper">
                    <% @genres.each do |genre| %>
                    <span><%= genre.genre_name %>
                    <%# <%= link_to '編集' , edit_admin_genre_path(genre) %>
                    <button type="button" name="削除" value="<%=genre.id%>" class="genre_delete">削除</button>
                    </span>
                    <%#= link_to '削除' , admin_genre_path(genre), method: :delete, id: "genre_delete", remote: true, data: {genre_id: genre.id} %>
                    <% end %>
                </div>
                <br>
                <br>
                <br>
                <h2>ジャンル追加</h2>
                <div>
                    <%= form_for [:admin, @genre], url: admin_genres_path, method: :POST, remote: false do |f| %>
                    <p><%= f.text_field :genre_name %></p>
                    <p><%= f.submit 'ジャンルを追加する', id: "genre_submit" %></p>
                    <% end %>
                </div>
                <div class="col-sm-4"></div>
            </div>
        </div>


        <div>レーベル</div>
        <%= f.collection_select :label_id, Label.all, :id, :label_name %>

        <div class="new_button label_button">レーベルを追加する</div>

        <div class="label_modal_wrapper">
            <div class="label_modal label_modal_content">
                <p class="text-right">
                <span class="fa_wrapper"><%= fa_icon "times" %></span>
                </p>
                <h1>レーベル追加フォーム</h1>
                <h2>追加済みレーベル一覧</h2>
                <div class="label_wrapper">
                    <% @labels.each do |label| %>
                    <span><%= label.label_name %>
                    <%# <%= link_to '編集' , edit_admin_label_path(label) %>
                    <button type="button" name="削除" value="<%=label.id%>" class="label_delete">削除</button>
                    </span>
                    <% end %>
                </div>
                <br>
                <br>
                <br>
                <h2>レーベル追加</h2>
                <div>
                    <%= form_for [:admin, @label], url: admin_labels_path, method: :POST, remote: false do |f| %>
                    <p><%= f.text_field :label_name %></p>
                    <p><%= f.submit 'レーベルを追加する', id: "label_submit" %></p>
                    <% end %>
                </div>
            </div>
        </div>

        <div>値段</div>
        <p><%= f.text_field :amount %></p>

        <ul><%= f.submit '新規商品の登録をする' %></ul>
        <% end %>

    </div>
            <div class="artist_modal_wrapper">
            <div class="artist_modal artist_modal_content">
                <p class="text-right">
                <span class="fa_wrapper"><%= fa_icon "times" %></span>
                </p>
                <h1>アーティスト追加フォーム</h1>
                <h2>追加済みアーティスト一覧</h2>
                <div class="artist_wrapper">
                    <% @artists.each do |artist| %>
                    <span><%= artist.artist_name %>
                    <%#= link_to '編集' , admin_artist_path(artist), method: PUT %>
                    <button type="button" name="削除" value="<%=artist.id%>" class="artist_delete">削除</button>
                    </span>
                    <% end %>
                </div>
                <br>
                <br>
                <br>
                <h2>アーティスト追加</h2>
                <div>
                    <%= form_for [:admin, @artist], url: admin_artists_path, method: :POST, remote: false do |f| %>
                    <p><%= f.text_field :artist_name %></p>
                    <p><%= f.submit 'アーティストを追加する', id: "artist_submit" %></p>
                    <% end %>
                </div>
            </div>
        </div>

</div>

app/views/admin/products/show.html.erb
<div class="container">
    <h1>商品詳細</h1>
    <hr>
    <br>
    <br>

    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div>
            <%= attachment_image_tag @product, :image, :fill, 100, 100, fallback: "default_product.jpg" , size:'200x200' %>
            </div>

            <h2>商品名：<%= @product.title %></h2>
            <hr>

            <h2>価格：¥<%= @product.amount %>(税抜)</h2>
            <hr>

            <h2>在庫数：
            <%= productquantity = @product.arrivals.sum(:quantity) - @product.order_details.sum(:quantity) %></h2>
            <hr>

            <h2>販売状況</h2>
            <% if productquantity == 0 %>
            <h2>売り切れ</h2>
            <% else %>
            <h2>販売中</h2>
            <% end %>
            <hr>
            <h2>アーティスト：<%= @product.artist.artist_name %></h2>
            <hr>

            <h2>レーベル：<%= @product.label.label_name %></h2>
            <hr>

            <h2>ジャンル：<%= @product.genre.genre_name %></h2>
            <hr>


            <h2>ディスク名</h2>
            <% @product.discs.each do |disc| %> 
            <%= disc.disc_number %>
            <h2>収録曲一覧</h2>
            <% disc.musics.each do |music| %> 
            <%= music.music_name %> 
            <% end %> 
            <% end %> 
            <hr>
            <h2>商品紹介</h2>
            <div>
            <%= @product.explanation %>
            </div>
            <hr>
            <div class="botton-wrapper">
            <%= link_to "商品の情報を編集する" , edit_admin_product_path(@product), class: 'btn btn-default' %>
            </div>
            <hr>
            <div class="botton-wrapper">
            <%= link_to "商品一覧へ" , admin_products_path, class: 'btn btn-info' %>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>