config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'products#index'
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/password',
      registrations: 'admins/registrations'
    }
    devise_for :end_users, controllers: {
      sessions:      'end_users/sessions',
      password:      'end_users/password',
      registrations: 'end_users/registrations'
    }
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
    resources :order_details, only: [:index]
    end
    resources :orders, only: [:index, :show, :update]

    resources :products, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :arrivals, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :artists, only: [:new, :edit, :create, :update, :destroy]
    resources :labels, only: [:new, :edit, :create, :update, :destroy]
    resources :genres, only: [:new, :edit, :create, :update, :destroy]

    get  'top' => 'homes#top'
    get  'out/end_users/:id', to: 'end_users#out', as: :out
    get  'change' => 'order_details#change'
  end   
  resources :end_users, only: [:show, :edit, :destroy, :update] do 
    resources :addresses, only: [:create]
  end
  post '/orders/confirm', to: 'orders#before_confirm'
  get '/orders/confirm', to: 'orders#confirm', as: :confirm_order
  get '/orders/finish', to: 'orders#finish', as: :finish_order
  resources :orders, only: [:index, :show, :new, :create]
  resources :order_details, only: [:index]
  resources :cart_products, only: [:index, :update, :create, :destroy]
  resources :products, only: [:index, :show]
  get  'out' => 'end_users#out'
  
end

app/models/address.rb
class Address < ApplicationRecord
    validates :delivery_name, presence: true
    validates :delivery_postal_code, presence: true
    validates :delivery_address, presence: true

    belongs_to :end_user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrival.rb
class Arrival < ApplicationRecord
    validates :quantity, :arrival_time, presence: true

    belongs_to :product
    
end

app/models/artist.rb
class Artist < ApplicationRecord
    validates :artist_name, presence: true
    has_many :products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :end_user
    belongs_to :product

    validates :quantity, :numericality => { :greater_than_or_equal_to => 1 }, presence: true

    def total_arrival_quantity
        total_arrival_quantity = 0
        arrivals.each do |arrival|
            total_arrival_quantity = arrival.quantity + total_arrival_quantity
        end
        total_arrival_quantity
    end

    def total_order_detail_quantity
        total_order_detail_quantity = 0
        order_details.each do |order_detail|
            unless order_detail.quantity.nil?
                total_order_detail_quantity = order_detail.quantity + total_order_detail_quantity
            
        end
        total_order_detail_quantity
    end

end

app/models/disc.rb
class Disc < ApplicationRecord
    
    validates :disc_number, presence: true
    belongs_to :product
    has_many :musics , inverse_of: :disc
    accepts_nested_attributes_for :musics , reject_if: :all_blank , allow_destroy: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :main_postal_code, presence: true
  validates :main_address, presence: true
  validates :phone_number, presence: true
  





  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  # accepts_nested_attributes_for :addresses

  def cart_total_price
    total_price = 0
    self.cart_products.each do |cart_product|
      total_price += cart_product.product.amount * cart_product.quantity
    end
    return total_price
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :genre_name, presence: true
    has_many :products
end

app/models/label.rb
class Label < ApplicationRecord
    validates :label_name, presence: true
    has_many :products
end

app/models/music.rb
class Music < ApplicationRecord
    validates :music_name, presence: true
    belongs_to :disc
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details, dependent: :destroy
    belongs_to :end_user
    enum payment_method: {銀行振込: 0,クレジットカード支払い: 1, 代引き: 2}
    enum delivery_status: {受付: 0, 商品準備中: 1, 出荷済: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [['---',""],['売り切れ', 1],['販売中', 2]]
    acts_as_paranoid
    def total_arrival_quantity
        total_arrival_quantity = 0
        arrivals.each do |arrival|
        total_arrival_quantity = arrival.quantity + total_arrival_quantity
            unless arrival.quantity.nil?
                total_arrival_quantity = arrival.quantity + total_arrival_quantity

            end
        end
        total_arrival_quantity
    end

    def total_order_detail_quantity
        total_order_detail_quantity = 0
        order_details.each do |order_detail|
            unless order_detail.quantity.nil?
                total_order_detail_quantity = order_detail.quantity + total_order_detail_quantity
        
            end
        end
        total_order_detail_quantity
    end

    def included_price
        included_price = (amount * 1.1).floor(0)
    end

    validates :title, presence: true
    validates :explanation, presence: true
    validates :amount, presence: true
    attachment :image

    has_many :discs, inverse_of: :product
    accepts_nested_attributes_for :discs , reject_if: :all_blank , allow_destroy: true

    belongs_to :artist 
    belongs_to :genre
    belongs_to :label
    has_many :arrivals
    has_many :order_details
    has_many :cart_products
    has_many :order_details

end

app/controllers/admin/arrivals_controller.rb
class Admin::ArrivalsController < Admin::Base
    before_action :authenticate_admin!

    PER = 5
def index
    @arrival = Arrival.new
    @arrivals = Arrival.page(params[:page]).per(PER)
end
def new
    @arrival = Arrival.new

end 
def edit
    @arrival = Arrival.find(params[:id])
end
def create
    @arrival = Arrival.new(arrival_params)
    if
    @arrival.save
    redirect_to admin_arrivals_path
    else
    render :new
    end
end
def update
    arrival = Arrival.find(params[:id])
    if arrival.update(arrival_params)
        redirect_to admin_arrivals_path
    else
        render :edit
    end
end
def destroy
    arrival = Arrival.find_by(id:params[:id])
    if arrival.destroy
    redirect_to admin_arrivals_path
    else
    render :edit
    end
end

private
def arrival_params
    params.require(:arrival).permit(:product_id, :quantity, :arrival_date, :arrival_time)
end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/arrivals_helper.rb
module Admin::ArrivalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/arrivals/edit.html.erb
<div class= "container">
    <h1>入荷情報編集</h1>
    <%= form_for([:admin, @arrival]) do |arrival| %>
        <div class= "field">
            <p>シングル/アルバム名</p>
            <%= arrival.select :product_id, Product.all.map {|p| [p.title, p.id]} %>
        </div><br>
        <div class= "field">
            <p>数量</p>
            <%= arrival.number_field :quantity, min: 1 %>
        </div><br>
        <div class= "field">
            <p>入荷日時</p>
            <%= arrival.datetime_select :arrival_time, class: 'form-control'%>
        </div><br>

        <%= arrival.submit %>
        <br>
        <br>

        <div class= "button-wrapper">
            <%= link_to "削除する", admin_arrival_path(@arrival), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-danger' %>
        </div>
        <div>
        <br>
            <%= link_to "戻る", admin_arrivals_path %>
    <% end %>
</div>

app/views/admin/arrivals/index.html.erb
<div class= "container">
    <div class= "page-header">
        <h1><strong>入荷履歴一覧</strong></h1>
    </div>
    <div class="list-group">
        <table class= "table">
            <tr>
                <th>商品名</th>
                <th>数量</th>
                <th>入荷日時</th>
                <th></th>
            </tr>
        <% @arrivals.each do |arrival| %>
            <tr>
                <td><%= Product.with_deleted.find(arrival.product_id).title %></td>
                <td><%= arrival.quantity %></td>
                <td><%= arrival.arrival_time.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒") %></td>
                <td><%= link_to edit_admin_arrival_path(arrival) do %>
                <i>編集</i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
            <div class="center">
                <%= paginate @arrivals %>
            </div>
            <div class="button_wrapper">
                <%= link_to "入荷情報追加", new_admin_arrival_path, class: 'btn' %>
            </div>
    </div>
</div>

app/views/admin/arrivals/new.html.erb
<div class= "container">
<h1>入荷情報追加フォーム</h1>
<%= form_for([:admin, @arrival]) do |arrival| %>
    <div class= "field">
    <p>シングル/アルバム名</p>
    
    <%= arrival.select :product_id, Product.all.map {|p| [p.title, p.id]} %>
    </div><br>
    <div class= "field">
    <hr>
    <p>数量</p>
    <%= arrival.number_field :quantity, min: 1, value: 1 %>
    </div><br>
    <div class= "field">
    <p>入荷日時</p>
    <%= arrival.datetime_select :arrival_time, class: 'form-control' %>
    </div><br>
    <%= arrival.submit %>

<% end %>
</div>